### PR TITLE
docx5j improvements (word wrapping and Cell Merging)

### PR DESCRIPTION
**Pull request by jposterloh**
Hi, 

thank you very much for your great library, that saved me a lot of work!

I added two things I needed, first I wanted word wrapping in a cell, thus I added another setAlignment method in the StyleBuilder, and second I needed to merge some cells, so I added this into the Worksheet builder. It requires the Range to merge in the form "A1:A3", if you have a better solution, please let me know, I will fix it if possible. 

Best regards
Jan-Patrick

### CODE REVIEW

**Comment by jposterloh** [comment]
P.S. you hardcoded some files in the test, I removed that for me, as it could not generate the files in this path

**Comment by matchami** [comment]
Hi Jan-Patrick,

Thanks for your great contribution (and thanks for using docx5j :).  More than happy to merge this - just have one place I'd like to understand your methodology: you've added the 

public void setValue(int sheet, int col, int row, String value, Long style) ...

method which is great.  And you're passing styles.get("") to signify no style I think?  Is that correct?  

Could we achieve the same thing by passing (Long)null instead?  This would resolve the null ambiguity which I guess is why you chose this methodology (?) but also save having to do a needless hash calculation.  Does that sound like it would work to you?

Thanks
Iain

**Comment by jposterloh** [comment]
Hi, 

you are right, I did this to solve the null ambiguity. I didn't know that you can cast a null :-) Learned something new, thanks! I fixed and pushed it. 

Best 
Jan-Patrick

**Comment by matchami** [comment]
Hi Jan-Patrick,
Thank you again for your contribution to the project :)  I've merged your pull request to the master branch 
Thanks
Iain

**Pull request merged**
